import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Add a fallback class to avoid mismatches */}
      <body
        className={`antialiased relative w-full overflow-x-hidden scroll-smooth overflow-x-hidden`}
      >
        <Navigation />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
