import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative w-full scroll-smooth antialiased">
        <Navigation />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
